service: step-functions-demo

frameworkVersion: "3"

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2

functions:
  hello:
    handler: handler.hello
